### PR TITLE
Get hot reloading to work for development

### PR DESCRIPTION
**Pull request by kumar303**
This attempts to work around hot reloading issues: https://github.com/mozilla/addons-code-manager/issues/275

### CODE REVIEW

**Comment by kumar303** [comment]
@bobsilverberg @willdurand What do you think? Is this too crazy? I dislike straying from `react-scripts`. This might be OK just as a temporary solution until the upstream issues is resolved, though?

It fixes the issue for me using the STR in https://github.com/mozilla/addons-code-manager/issues/275

**Comment by willdurand** [comment]
If this patch fixes the issue, that's a good think because we'll likely need hot reload soon (that was not super useful until then). Yet, this will make upgrades more complicated (or even maybe impossible...) and temporary workarounds usually last for a very long time (not to say forever).

The README of this rewire project says: "As of Create React App 2.0 this repo is "lightly" maintained mostly by the community at this point."

What are our other options? Could we try to fix CRA instead?

**Comment by kumar303** [comment]
> Could we try to fix CRA instead?

I guess it just involves [updating the loaders](https://github.com/cdharris/react-app-rewire-hot-loader/blob/331a8dd34cc9c4af50e37d362d6b8e66ef62d0fe/index.js).

**Comment by bobsilverberg** [comment]
Should this be closed? Do we now have hot reloading working?

**Comment by willdurand** [comment]
ah, yes.

**Pull request closed without merging**
