### PR TITLE
Indicate file diff status in FileTreeNode

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/addons-code-manager/issues/413

I didn't have time to add a story but we could do that in https://github.com/mozilla/addons-code-manager/issues/431 💳 

Examples, mostly from http://localhost:3000/en-US/compare/616645/versions/1655530...1655531/?path=scripts/background.js

Screenshot 2019-05-17 11 41 50
Screenshot 2019-05-17 11 42 07
Screenshot 2019-05-17 11 42 30
Screenshot 2019-05-17 11 42 51

### CODE REVIEW

**Comment by willdurand** [comment]
I like the UI for that but I am confused by the colors. What's the meaning of each color? (Edit: it's in the code but from the screenshots, I could not get it).

I hardly see the difference between the green and red ones, so I'd like to see another visual indicator or a better color contrast. Maybe we could have the letters `A`, `M` and `D`.

**Comment by kumar303** [comment]
> I like the UI for that but I am confused by the colors. What's the meaning of each color? (Edit: it's in the code but from the screenshots, I could not get it).

I intended to loosely match the colors of an actual diff:

Screenshot 2019-05-15 09 30 58


That is, green for *added* and red for *deleted*. The orange for *modified* doesn't exist in diffs but that was just to indicate that something was both deleted and added. I suppose *modified* could be green.

> 
> I hardly see the difference between the green and red ones, so I'd like to see another visual indicator or a better color contrast. Maybe we could have the letters `A`, `M` and `D`.

Ah, good point. I'll see if I can add the letters to it.

**Comment by kumar303** [comment]
@willdurand does the pink and green line highlights from the screenshot in https://github.com/mozilla/addons-code-manager/pull/728#issuecomment-492681617 have enough contrast for you? I could follow those colors.

I may leave the addition of showing a letter (`A`, `D`) for a follow-up, just to keep it moving.

Even if the contrast between deleted and modified is not high enough for some folks, that's probably OK. It's more important that one can immediately spot a *changed* file / directory in the tree.

**Comment by willdurand** [comment]
@kumar303 yep, these pink and green colors are ok. Maybe we could add html titles at least, and ship the letters later..

**Comment by willdurand** [comment]
I quickly retried this patch and the colors look a bit better, maybe a bit too pale but at least distinguishable.

**Comment by kumar303** [comment]
@willdurand I darkened the colors slightly. What do you think? The contrast still fails ﻿﻿https://color.review/ but it's better than before. If I darken it much more, the hues will become too close on the visible spectrum.

**Comment by willdurand** [comment]
> @willdurand I darkened the colors slightly. What do you think? The contrast still fails ﻿﻿[color.review](https://color.review/) but it's better than before. If I darken it much more, the hues will become too close on the visible spectrum.

The new contrast passed my validator 😛 

I suppose the idea of having letters (or `+/~/-` signs, maybe) in addition to the colors would solve what you mention in your last sentence.

**Pull request merged**
