### PR TITLE
Move shared utils to src/utils.tsx

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-code-manager/issues/1351

### CODE REVIEW

**Comment by willdurand** [comment]
> Looks good, @willdurand, but why does it fix #1351?

ah sorry, I should have mentioned this. There was a circular dependency and that caused the function to not be injected correctly in the bundle generated by webpack :/

**Comment by bobsilverberg** [comment]
> > Looks good, @willdurand, but why does it fix #1351?
> 
> ah sorry, I should have mentioned this. There was a circular dependency and that caused the function to not be injected correctly in the bundle generated by webpack :/

Ah, that makes sense! It seems odd that none of our tests, nor even `tsc`, caught this. Does that surprise you, or is that expected?

**Comment by willdurand** [comment]
> Ah, that makes sense! It seems odd that none of our tests, nor even `tsc`, caught this. Does that surprise you, or is that expected?

The fact that the CI did not catch this problem does not surprise me because we are not testing the bundle generated by webpack. What surprises me is that I did not catch it locally before, though.

Circular dependencies are hard to detect. There are webpack plugins for that and I thought webpack was smart enough to detect them too...

**Comment by bobsilverberg** [comment]
> > Ah, that makes sense! It seems odd that none of our tests, nor even `tsc`, caught this. Does that surprise you, or is that expected?
> 
> The fact that the CI did not catch this problem does not surprise me because we are not testing the bundle generated by webpack. What surprises me is that I did not catch it locally before, though.
> 
> Circular dependencies are hard to detect. There are webpack plugins for that and I thought webpack was smart enough to detect them too...

Yes, I should have caught this even before creating the PR. I guess I only manually tested the CodeView and not the DiffView.

**Pull request merged**
