### PR TITLE
[WIP] Adds a FixedMetaNav for left-hand controls

### PR DESCRIPTION
**Pull request by kumar303**
I had a thought to experiment with a fixed file tree to make it easier to know where you are in the tree.

<details>
<summary>Screencast</summary>

</details>

@bobsilverberg @willdurand what do you think?

### CODE REVIEW

**Comment by bobsilverberg** [comment]
I like it. I found it a bit inconsistent though. For example, if you put your mouse over the left nav, and scroll all the way to the bottom, once you reach the bottom it starts scrolling the file content as well. But if you put your mouse over the file content, and scroll all the way to the bottom, it doesn't scroll the left-hand nav.

I don't think this is a big deal, but I thought I'd point it out.

I do like the fact that you can scroll the contents of the file and keep the tree static though - that's very nice.

**Comment by willdurand** [comment]
I did not play with the feature yet but I like the screencast a lot!

**Comment by kumar303** [comment]
It raises questions about how useful the screen real estate is *underneath* the file tree. We have been jamming a lot of stuff in there.

**Comment by kumar303** [comment]
Whoops, I meant to make this a draft PR. It's not actually ready for review 😄

**Comment by kumar303** [comment]
This feature is getting handled by related patches in a few other places. See https://github.com/mozilla/addons-code-manager/issues/582

I'm leaving it open just because I'll need to extract a few more bits.

**Comment by willdurand** [comment]
I am closing this PR because the feature has landed.

**Pull request closed without merging**
