### PR TITLE
Add FileMetadata in browse page

### LINKED ISSUE #326: Implement footer for file viewer
This is an issue that was discussed in our review of the current reviewer tools and I neglected to file.

The file viewer should contain a footer which should include at least the file hash and a ~~download link~~ (this will be added in https://github.com/mozilla/addons-code-manager/issues/353) for the file.

We should add a screenshot of the current footer to this issue.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #326

---

Screen Shot 2019-03-15 at 11 27 53

### CODE REVIEW

**Comment by willdurand** [comment]
Rebased!

**Comment by kumar303** [comment]
Hmm. The screenshot you put in the description suggests that the hash overflow is fixed but I still see it after building your branch just now. Did something regress?

Screenshot 2019-03-19 11 18 54

**Comment by willdurand** [comment]
@kumar303 mmh 🤔  I just rebased and `yarn && yarn dev`:

Screen Shot 2019-03-19 at 16 10 34

I pushed the rebased version of this patch, just in case.

**Comment by kumar303** [comment]
I develop with Firefox release (currently 66) and `break-word` is not supported there. From [this thread](https://stackoverflow.com/questions/47413677/alternative-for-word-break-break-word) it looks like you can use `break-all`. 

I guess `break-word` was added in an older patch?

**Comment by willdurand** [comment]
> I develop with Firefox release (currently 66) and `break-word` is not supported there. From [this thread](https://stackoverflow.com/questions/47413677/alternative-for-word-break-break-word) it looks like you can use `break-all`.

Oh, ok.
 
> I guess `break-word` was added in an older patch?

Isn't it part of Bootstrap? I don't see any occurrence of `break-word` in the code.

**Comment by kumar303** [comment]
Ah, probably. We can probably override it for just this component. Feel free to file it as a separate issue since it's not related to your patch.

**Comment by willdurand** [comment]
> Ah, probably. We can probably override it for just this component. Feel free to file it as a separate issue since it's not related to your patch.

I filed https://github.com/mozilla/addons-code-manager/issues/424

**Comment by willdurand** [comment]
> This looks good to ship. I dislike the UI positioning of it, though. When there's a big list of files, it will get pushed all the way to the bottom. One alternative would be to make it an absolute positioned panel that always floats in the lower left corner. I haven't fully thought that through but it's just something that came to mind. We can revisit this later.

Once we have loading indicators (#379), I'd like to move this component above the file tree.

**Pull request merged**
